n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('É alfabético?', (n.isalpha()))
print('É alfanumerico?', (n.isalnum()))
print('É um número?', (n.isnumeric()))
print('Só tem espaços?', (n.isdigit()))
print('Só tem letras maiusculas?', (n.isupper()))
print('Só tem letras minusculas?', (n.islower()))
print('Fim')